CLASS zbp_i_employee DEFINITION
    PUBLIC
    ABSTRACT
    FINAL
    FOR BEHAVIOR OF zi_employee.
  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZBP_I_EMPLOYEE IMPLEMENTATION.
ENDCLASS.
